### ISSUE TITLE
[Crash] "Can only send to ServerPlayerEntities!"

### ISSUE THREAD

**Issue by Fogrits** [vini2003/Shest#2]
java.lang.RuntimeException: Can only send to ServerPlayerEntities!
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.3)
    at net.fabricmc.fabric.impl.networking.ServerSidePacketRegistryImpl.sendToPlayer(ServerSidePacketRegistryImpl.java:83)
    at net.fabricmc.fabric.api.network.ServerSidePacketRegistry.sendToPlayer(ServerSidePacketRegistry.java:72)
    at net.fabricmc.fabric.api.network.ServerSidePacketRegistry.sendToPlayer(ServerSidePacketRegistry.java:93)
    at spinnery.common.BaseContainer.onContentChanged(BaseContainer.java:233)
    at shest.common.ShestContainer$$Lambda$5359/0000000000000000.onInvChange(Unknown Source)
    at shest.entity.ShestBlockEntity.lambda$onInvChange$0(ShestBlockEntity.java:121)
    at shest.entity.ShestBlockEntity$$Lambda$5355/0000000000000000.accept(Unknown Source)
    at java.util.ArrayList.forEach(ArrayList.java:1507)
    at shest.entity.ShestBlockEntity.onInvChange(ShestBlockEntity.java:121)
    at shest.entity.ShestBlockEntity.setInvStack(ShestBlockEntity.java:104)
    at spinnery.widget.WSlot.setStack(WSlot.java:253)
    at spinnery.common.BaseContainer.onSlotClicked(BaseContainer.java:169)
    at spinnery.widget.WSlot.onMouseClicked(WSlot.java:149)
    at spinnery.widget.WInterfaceHolder.onMouseClicked(WInterfaceHolder.java:60)
    at spinnery.common.BaseContainerScreen.mouseClicked(BaseContainerScreen.java:99)
    at net.minecraft.client.Mouse.method_1611(Mouse:86)
    at net.minecraft.class_312$$Lambda$3130/0000000000000000.run(Unknown Source)
    at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:447)
    at net.minecraft.client.Mouse.onMouseButton(Mouse:86)
    at net.minecraft.client.Mouse.method_22686(Mouse:150)
    at net.minecraft.class_312$$Lambda$2910/0000000000000000.run(Unknown Source)
    at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:94)
    at net.minecraft.client.Mouse.method_22684(Mouse:150)
    at net.minecraft.class_312$$Lambda$2552/0000000000000000.invoke(Unknown Source)
    at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
    at org.lwjgl.system.JNI.invokeV(Native Method)
    at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
    at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem:98)
    at net.minecraft.client.util.Window.swapBuffers(Window:301)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1012)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:619)
    at net.minecraft.client.main.Main.main(Main:204)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:567)
    at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:193)
    at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:138)
    at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

Shest 1.2.1

**Comment by Fogrits** [comment]
Happened while shift clicking a stack of wood into the shest

**Comment by vini2003** [comment]
Should be fixed in `1.2.2`.

**Comment by Fogrits** [comment]
Ah, forgot to mention... the block doesn't drop when I break it :P

**Comment by vini2003** [comment]
Oh god, oh fuck.

**Comment by Fogrits** [comment]
but don't worry, the contents drop on the ground

**Comment by vini2003** [comment]
Alright, already fixed, will release ASAP.

**Comment by Fogrits** [comment]
thank you.

**Comment by Boundarybreaker** [comment]
@vini2003 It's back in 1.2.7! [crash link](https://gist.githubusercontent.com/Cloak-Bot/0a168ad532ca85a8623731652ac97d26/raw/ef40d223c46d459f6c5581417d78030843cd605f/crash.txt)

**Comment by vini2003** [comment]
Interestingly enough, turns out Shest 1.2.7 does *not* have the fix, which I'm damn sure it should have. I'll be updating it shortly.

**Comment by Boundarybreaker** [comment]
🤔

**Comment by vini2003** [comment]
Things became slightly more complicated than previously thought.
